/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;


import classfood.Profile;
import static java.lang.Integer.sum;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author yomi chan
 */
public class ProfileCustomer extends javax.swing.JFrame {

    /**
     * Creates new form Profile
     */
    
    public ProfileCustomer() {
        initComponents();
        getConnection();
        JTable_P();
        
    }
    
   String uname;
    public ProfileCustomer(String val1){
        initComponents();
        JTable_P();
        
        this.uname=val1;
        
        
        Adddata();   
    }

    void Adddata(){
        
        this.uuname.setText(""+uname);
             
    }
    
    
    
    
    

    public Connection getConnection()
    {
        Connection con = null;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/order?zeroDateTimeBehavior=convertToNull","root","");
            return con;
        } catch (SQLException ex) {
            Logger.getLogger(ProfileCustomer.class.getName()).log(Level.SEVERE, null, ex);
            return null;
        }
    }
    
    // get a list of users from mysql database
   public ArrayList<Profile> getProfileList()
   {
       ArrayList<Profile> ProfileList = new ArrayList<Profile>();
       Connection connection = getConnection();
       
       String query = "SELECT * FROM `Customer`";
       Statement st;
       ResultSet rs;
       
       try {
           st = connection.createStatement();
           rs = st.executeQuery(query);
           Profile NewP;
           while(rs.next())
           {
               NewP = new Profile(rs.getInt("ID_C"),rs.getString("Name"),rs.getString("NumPhone"),rs.getInt("NumTable"),rs.getString("Date"));
               ProfileList.add(NewP);
           }
       } catch (Exception e) {
           e.printStackTrace();
       }
       return ProfileList;
   }
   
   
    public void JTable_P()
   {
       ArrayList<Profile> list = getProfileList();
       DefaultTableModel model = (DefaultTableModel)DTable_P.getModel();
       Object[] row = new Object[5];
       for(int i = 0; i < list.size(); i++)
       {
           row[0] = list.get(i).getID();
           row[1] = list.get(i).getName();
           row[2] = list.get(i).getNumPhone();
           row[3] = list.get(i).getNumTable();
           row[4] = list.get(i).getDate();
           model.addRow(row);
       }
    }
    
    
     // Execute The Insert Update And Delete Querys
    public void executeSQlQuery_P(String query, String message)
   {
       Connection con = getConnection();
       Statement st;
       try{
           st = con.createStatement();
           if((st.executeUpdate(query)) == 1)
           {
               // refresh jtable data
               DefaultTableModel model = (DefaultTableModel)DTable_P.getModel();
               model.setRowCount(0);
               JTable_P();
        
               
           }else{
               
           }
       }catch(Exception ex){
           ex.printStackTrace();
       }
   }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DTable_P = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Next = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        id_p = new javax.swing.JTextField();
        Date_P = new javax.swing.JTextField();
        Numphone_P = new javax.swing.JTextField();
        Numtable_P = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Name_P = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        Add_P = new javax.swing.JButton();
        Delete_P = new javax.swing.JButton();
        Update_P = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        uuname = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/125.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(610, 350));
        setPreferredSize(new java.awt.Dimension(760, 380));
        setSize(new java.awt.Dimension(740, 400));
        getContentPane().setLayout(null);

        DTable_P.setBackground(new java.awt.Color(255, 204, 204));
        DTable_P.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "NumPhone", "NumTable", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        DTable_P.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DTable_PMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(DTable_P);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 160, 380, 180);

        jLabel20.setFont(new java.awt.Font("teddy", 1, 20)); // NOI18N
        jLabel20.setText("ID");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(490, 160, 50, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Hungry-icon.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 110, 50, 40);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Mayor-icon.png"))); // NOI18N
        getContentPane().add(jLabel19);
        jLabel19.setBounds(420, 160, 50, 50);

        Next.setFont(new java.awt.Font("teddy", 0, 16)); // NOI18N
        Next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/next.png"))); // NOI18N
        Next.setText("Next");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });
        getContentPane().add(Next);
        Next.setBounds(640, 310, 80, 33);

        jLabel3.setFont(new java.awt.Font("Action Man Shaded", 1, 60)); // NOI18N
        jLabel3.setText("CUSTOMER   PROFILE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 10, 730, 100);

        id_p.setBorder(null);
        getContentPane().add(id_p);
        id_p.setBounds(530, 160, 185, 20);

        Date_P.setText("dd/mm/yyyy");
        Date_P.setBorder(null);
        getContentPane().add(Date_P);
        Date_P.setBounds(530, 280, 185, 20);

        Numphone_P.setBorder(null);
        getContentPane().add(Numphone_P);
        Numphone_P.setBounds(530, 220, 185, 20);

        Numtable_P.setBorder(null);
        getContentPane().add(Numtable_P);
        Numtable_P.setBounds(530, 250, 185, 20);

        jLabel17.setFont(new java.awt.Font("teddy", 1, 20)); // NOI18N
        jLabel17.setText("Name");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(470, 190, 50, 24);

        jLabel18.setFont(new java.awt.Font("teddy", 1, 20)); // NOI18N
        jLabel18.setText("NumPhone");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(430, 220, 100, 24);

        jLabel15.setFont(new java.awt.Font("teddy", 1, 20)); // NOI18N
        jLabel15.setText("NumTable");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(440, 250, 71, 24);

        Name_P.setBorder(null);
        getContentPane().add(Name_P);
        Name_P.setBounds(530, 190, 185, 20);

        jLabel16.setFont(new java.awt.Font("teddy", 1, 20)); // NOI18N
        jLabel16.setText("Date");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(470, 280, 40, 24);

        Add_P.setFont(new java.awt.Font("teddy", 0, 16)); // NOI18N
        Add_P.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/return.png"))); // NOI18N
        Add_P.setText("Add");
        Add_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_PActionPerformed(evt);
            }
        });
        getContentPane().add(Add_P);
        Add_P.setBounds(420, 310, 80, 33);

        Delete_P.setFont(new java.awt.Font("teddy", 0, 16)); // NOI18N
        Delete_P.setText("Delete");
        Delete_P.setMaximumSize(new java.awt.Dimension(88, 33));
        Delete_P.setMinimumSize(new java.awt.Dimension(88, 33));
        Delete_P.setPreferredSize(new java.awt.Dimension(88, 33));
        Delete_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_PActionPerformed(evt);
            }
        });
        getContentPane().add(Delete_P);
        Delete_P.setBounds(500, 310, 70, 33);

        Update_P.setFont(new java.awt.Font("teddy", 0, 16)); // NOI18N
        Update_P.setText("Update");
        Update_P.setMaximumSize(new java.awt.Dimension(92, 33));
        Update_P.setMinimumSize(new java.awt.Dimension(92, 33));
        Update_P.setPreferredSize(new java.awt.Dimension(92, 33));
        Update_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_PActionPerformed(evt);
            }
        });
        getContentPane().add(Update_P);
        Update_P.setBounds(570, 310, 70, 33);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/125.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 760, 360);

        uuname.setText("jTextField1");
        getContentPane().add(uuname);
        uuname.setBounds(230, 210, 80, 26);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        setVisible(false);
        String idp = id_p.getText();
        String namep = Name_P.getText();
        String nump = Numphone_P.getText();
        String numt = Numtable_P.getText();
        String date = Date_P.getText();
        String uname = uuname.getText();
        new TableOrder(idp,namep,nump,numt,date,uname).setVisible(true);
    }//GEN-LAST:event_NextActionPerformed

    private void Delete_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_PActionPerformed
        String query = "DELETE FROM `Customer` WHERE ID_C = "+id_p.getText();
        executeSQlQuery_P(query, null);
    }//GEN-LAST:event_Delete_PActionPerformed

    private void Add_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_PActionPerformed
        String Query = "INSERT INTO Customer (ID_C,Name,NumPhone,NumTable,Date)values('"+id_p.getText()+"','"+Name_P.getText()+"','"+Numphone_P.getText()+"','"+Numtable_P.getText()+"','"+Date_P.getText()+"')";
        executeSQlQuery_P(Query, null);  
    }//GEN-LAST:event_Add_PActionPerformed

    private void Update_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_PActionPerformed
        String query = "UPDATE `Customer` SET `Name`='"+Name_P.getText()+"',`NumPhone`='"+Numphone_P.getText()+"',`NumTable`="+Numtable_P.getText()+",`Date`="+Date_P.getText()+" WHERE `ID_C` = "+id_p.getText();
        executeSQlQuery_P(query, null);
    }//GEN-LAST:event_Update_PActionPerformed

    private void DTable_PMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DTable_PMouseClicked
        int i = DTable_P.getSelectedRow();
        TableModel model = DTable_P.getModel();
        id_p.setText(model.getValueAt(i,0).toString());
        Name_P.setText(model.getValueAt(i,1).toString());
        Numphone_P.setText(model.getValueAt(i,2).toString());
        Numtable_P.setText(model.getValueAt(i,3).toString());
        Date_P.setText(model.getValueAt(i,4).toString());
    }//GEN-LAST:event_DTable_PMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfileCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfileCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfileCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfileCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfileCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_P;
    private javax.swing.JTable DTable_P;
    private javax.swing.JTextField Date_P;
    private javax.swing.JButton Delete_P;
    private javax.swing.JTextField Name_P;
    private javax.swing.JButton Next;
    private javax.swing.JTextField Numphone_P;
    private javax.swing.JTextField Numtable_P;
    private javax.swing.JButton Update_P;
    private javax.swing.JTextField id_p;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField uuname;
    // End of variables declaration//GEN-END:variables
}
