/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;


import classfood.orderlist;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yomi chan
 */
public class Total extends javax.swing.JFrame {

    /**
     * Creates new form Total
     */
    
    public Total() {
        initComponents();
        getConnection();
       
    }
    
    
    public Connection getConnection()
    {
        Connection con = null;
       
        
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/order?zeroDateTimeBehavior=convertToNull","root","");
            return con;
        } catch (SQLException ex) {
            Logger.getLogger(Total.class.getName()).log(Level.SEVERE, null, ex);
            return null;
        }
    }
    
    
 
    String idp, namep, nump,numt,date,uname, sum;
    
    public Total(String val1, String val2,String val3, String val4, String val5, String val6){
        initComponents();
        this.idp=val1;
        this.namep=val2;
        this.nump=val3;
        this.numt=val4;
        this.uname=val5;
        this.date=val6;
        
        Adddata();
        
    }

    public Total(String val6){
        initComponents();
        
        this.sum=val6;
        
        Adddata();
        
    }

    void Adddata(){
        this.id_p.setText(""+idp);
        this.name_p.setText(""+namep);
        this.nump_p.setText(""+nump);
        this.numt_p.setText(""+numt);
        this.date_p.setText(""+date);
        this.uuname.setText(""+uname);
        this.s.setText(""+sum);        
    }
    
    
    public Total(String val1, String val2,String val3, String val4,String val5,String val6,String val7){
        initComponents();
         JTable_Ju();
        
        this.idp=val1;
        this.namep=val2;
        this.nump=val3;
        this.numt=val4;
        this.date=val5;
        this.uname=val6;
        this.sum=val7;
        
        Adddata();
                                    
    }
    
    
    
    
    public ArrayList<orderlist> getorderlistList()
   {
       ArrayList<orderlist> orderlistList = new ArrayList<orderlist>();
       Connection connection = getConnection();
       
       String query = "SELECT * FROM `Order_c`";
       Statement st;
       ResultSet rs;
       
       try {
           st = connection.createStatement();
           rs = st.executeQuery(query);
           orderlist NewJ;
           while(rs.next())
           {
               NewJ = new orderlist(rs.getInt("ID_C"),rs.getInt("sum"),rs.getString("username"));
               orderlistList.add(NewJ);
           }
       } catch (Exception e) {
           e.printStackTrace();
       }
       return orderlistList;
   }
   
   
    public void JTable_Ju()
   {
       ArrayList<orderlist> list = getorderlistList();
       DefaultTableModel model = (DefaultTableModel)TableC.getModel();
       Object[] row = new Object[3];
       for(int i = 0; i < list.size(); i++)
       {
           row[0] = list.get(i).getId_C();
           row[1] = list.get(i).getSum();
           row[2] = list.get(i).getUname();
           
           
           model.addRow(row);
       }
    }
    
    
     // Execute The Insert Update And Delete Querys
  
    public void executeSQlQuery_S(String query, String message)
   {
       Connection con = getConnection();
       Statement st;
       try{
           st = con.createStatement();
           if((st.executeUpdate(query)) == 1)
           {
               // refresh jtable data
               DefaultTableModel model = (DefaultTableModel)TableC.getModel();
               model.setRowCount(0);
               JTable_Ju();
               
               
           }else{
               
           }
       }catch(Exception ex){
           ex.printStackTrace();
       }
   }
    
    
    
    
    
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Amount = new javax.swing.JTextField();
        Change = new javax.swing.JButton();
        home = new javax.swing.JButton();
        name_p = new javax.swing.JLabel();
        nump_p = new javax.swing.JLabel();
        numt_p = new javax.swing.JLabel();
        date_p = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        id_p = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        s = new javax.swing.JLabel();
        change = new javax.swing.JLabel();
        uuname = new javax.swing.JTextField();
        Admin = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableC = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(640, 420));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Bloody-Mary-icon.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("teddy", 1, 20)); // NOI18N
        jLabel6.setText("Name");

        jLabel7.setFont(new java.awt.Font("teddy", 1, 20)); // NOI18N
        jLabel7.setText("NumPhone");

        jLabel8.setFont(new java.awt.Font("teddy", 1, 20)); // NOI18N
        jLabel8.setText("NumTable");

        jLabel9.setFont(new java.awt.Font("teddy", 1, 20)); // NOI18N
        jLabel9.setText("Date");

        jLabel10.setFont(new java.awt.Font("teddy", 0, 24)); // NOI18N
        jLabel10.setText("Amount Paid");

        Change.setFont(new java.awt.Font("teddy", 1, 18)); // NOI18N
        Change.setText("Change");
        Change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeActionPerformed(evt);
            }
        });

        home.setFont(new java.awt.Font("teddy", 1, 18)); // NOI18N
        home.setText("Finish");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        name_p.setFont(new java.awt.Font("Waffle Regular", 1, 24)); // NOI18N

        nump_p.setFont(new java.awt.Font("Waffle Regular", 1, 24)); // NOI18N

        numt_p.setFont(new java.awt.Font("Waffle Regular", 1, 24)); // NOI18N

        date_p.setFont(new java.awt.Font("Waffle Regular", 1, 24)); // NOI18N

        jLabel13.setFont(new java.awt.Font("teddy", 1, 20)); // NOI18N
        jLabel13.setText("ID");

        id_p.setFont(new java.awt.Font("Waffle Regular", 0, 24)); // NOI18N
        id_p.setText("jLabel14");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Amount, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Change, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6)
                    .addComponent(jLabel13))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id_p)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(name_p, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                        .addComponent(nump_p, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(numt_p, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(date_p, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(id_p))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name_p, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(nump_p, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(numt_p, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(date_p, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Amount, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Change, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(home)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(64, 64, 64))))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 120, 390, 280);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        jLabel1.setFont(new java.awt.Font("Action Man Shaded", 1, 70)); // NOI18N
        jLabel1.setText("Total");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/aaaaaaaaa.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/aaaaaaaaa.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Pizza-icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(15, 15, 15))))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 640, 120);

        jPanel4.setBackground(new java.awt.Color(255, 255, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("teddy", 1, 24)); // NOI18N
        jLabel11.setText("Total Payable");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel12.setFont(new java.awt.Font("teddy", 1, 24)); // NOI18N
        jLabel12.setText("Change");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        s.setFont(new java.awt.Font("Waffle Regular", 1, 36)); // NOI18N
        s.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        s.setText("0.0");
        jPanel4.add(s, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 72, 25));

        change.setFont(new java.awt.Font("Waffle Regular", 1, 36)); // NOI18N
        change.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        change.setText("0.0");
        jPanel4.add(change, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 72, 25));

        uuname.setFont(new java.awt.Font("teddy", 1, 24)); // NOI18N
        uuname.setText("jTextField1");
        jPanel4.add(uuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 6, 117, 29));

        Admin.setFont(new java.awt.Font("teddy", 1, 24)); // NOI18N
        Admin.setText("Admin");
        jPanel4.add(Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 6, -1, -1));

        TableC.setBackground(new java.awt.Color(255, 255, 153));
        TableC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Custumer", "Total", "Seller"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableC);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 190, 120));

        getContentPane().add(jPanel4);
        jPanel4.setBounds(380, 120, 260, 280);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeActionPerformed
        String sum1 = s.getText();
        double sum2 = Double.parseDouble(sum1);
        double num1 = Double.parseDouble(Amount.getText());
        double num2 = num1-sum2;
        String num3 = Double.toString(num2);
        change.setText(num3);     
    }//GEN-LAST:event_ChangeActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        setVisible(false);
        
        
        
        this.id_p.setText(""+idp);
        
        this.uuname.setText(""+uname);
        this.s.setText(""+sum);  
        
        String Query = "INSERT INTO Order_c (ID_C,sum,username)values('"+id_p.getText()+"','"+s.getText()+"','"+uuname.getText()+"')";
        executeSQlQuery_S(Query, null);
       
        Home ob=new Home();
        ob.setVisible(true);
    }//GEN-LAST:event_homeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Total.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Total.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Total.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Total.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Total().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Admin;
    private javax.swing.JTextField Amount;
    private javax.swing.JButton Change;
    private javax.swing.JTable TableC;
    private javax.swing.JLabel change;
    private javax.swing.JLabel date_p;
    private javax.swing.JButton home;
    private javax.swing.JLabel id_p;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name_p;
    private javax.swing.JLabel nump_p;
    private javax.swing.JLabel numt_p;
    private javax.swing.JLabel s;
    private javax.swing.JTextField uuname;
    // End of variables declaration//GEN-END:variables
}
